<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Deloitte</name>
   <tag></tag>
   <elementGuidId>3f8c9266-7b27-4fb9-b2f8-a08aa23a8713</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#firstHeading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='firstHeading']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>99fbf897-38d7-4bf1-84f9-4e7403475edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>firstHeading</value>
      <webElementGuid>ed08ca0a-d0cd-4072-8bfb-55e4e61c3933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>firstHeading mw-first-heading</value>
      <webElementGuid>67767bd5-a2e1-4500-a002-e4c0f622ba46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Deloitte</value>
      <webElementGuid>74d548c3-b17d-4d59-92fa-1cd2ccd49758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;firstHeading&quot;)</value>
      <webElementGuid>adf2019c-b559-4c68-b284-9daf9a66114d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='firstHeading']</value>
      <webElementGuid>8b64dbc9-d70a-461f-a73b-23d354cf637a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content']/header/h1</value>
      <webElementGuid>a49d6897-22f8-46d9-a6d6-7f9eabb65a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>70d29eba-3495-4838-a4f3-effaeb891b86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'firstHeading' and (text() = 'Deloitte' or . = 'Deloitte')]</value>
      <webElementGuid>f99cb256-2977-49c7-92db-9d78797b0e52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
