<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Deloitte</name>
   <tag></tag>
   <elementGuidId>45b58354-3126-42f4-9241-8c347e28b5b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mw-page-title-main</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='firstHeading']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a8c7789e-803c-419f-ab1c-879996ff73e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mw-page-title-main</value>
      <webElementGuid>8510dbf5-b3ae-461a-9031-6a1105596cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Deloitte</value>
      <webElementGuid>170d588c-9c68-4f52-ad29-6935c42e8c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;firstHeading&quot;)/span[@class=&quot;mw-page-title-main&quot;]</value>
      <webElementGuid>0041a8fd-717e-479e-bdbd-a409175efc3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h1[@id='firstHeading']/span</value>
      <webElementGuid>03b5fb35-2003-4163-bef1-1f6198525c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>67a24fa5-976f-4934-8c4f-2aa6732e5105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Deloitte' or . = 'Deloitte')]</value>
      <webElementGuid>3ef7cf72-e43b-408f-b165-1bd33eaa4a9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
