<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputvector-main-menu-dropdown-checkbox</name>
   <tag></tag>
   <elementGuidId>213a3c8a-6fe4-486a-ad2f-20f9729e596d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vector-main-menu-dropdown-checkbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vector-main-menu-dropdown-checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>08a683e3-2aaf-4fd0-bb63-936d208229a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d144ae8a-5437-45d2-a59f-ecfb2825309c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vector-main-menu-dropdown-checkbox</value>
      <webElementGuid>17020f6d-ae53-4e22-a645-76a05a0d7954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>df6ae59d-0d5b-4a38-8b83-ef4c7b8ec4b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>daaf214c-1f42-4291-90fe-b8eda15cc3b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event-name</name>
      <type>Main</type>
      <value>ui.dropdown-vector-main-menu-dropdown</value>
      <webElementGuid>65a5f089-6a63-4641-b39b-f8863fcd2cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vector-dropdown-checkbox </value>
      <webElementGuid>1fbba431-5036-408d-b67a-461d1d3f2d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Main menu</value>
      <webElementGuid>790b7cee-95c3-4fa0-a875-5af08f855f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vector-main-menu-dropdown-checkbox&quot;)</value>
      <webElementGuid>063300b5-d159-4794-a71b-a29815cf3380</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vector-main-menu-dropdown-checkbox']</value>
      <webElementGuid>612a7b82-9eca-4c9b-9db0-c5f613c91d52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vector-main-menu-dropdown']/input</value>
      <webElementGuid>0003224c-35eb-4149-8c45-f69d57e3a2ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a8c93112-c23c-4556-adf9-eadf3818656b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'vector-main-menu-dropdown-checkbox']</value>
      <webElementGuid>11bf6a06-132c-4f70-9935-771f753f5b69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
