<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Katalon Studio</name>
   <tag></tag>
   <elementGuidId>99f6b447-1514-475f-ae5a-f21b89493d08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.cdx-search-result-title__match</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='cdx-menu-item-61']/a/span[2]/span/bdi/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0523425c-0e8d-4bba-8e1b-17d8d082730a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cdx-search-result-title__match</value>
      <webElementGuid>925382db-eb5a-4f10-8033-56e07e1063fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Katalon Studio</value>
      <webElementGuid>32517a8b-70f8-4bed-8374-f9b1ede41d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdx-menu-item-61&quot;)/a[@class=&quot;cdx-menu-item__content&quot;]/span[@class=&quot;cdx-menu-item__text&quot;]/span[@class=&quot;cdx-search-result-title&quot;]/bdi[1]/span[@class=&quot;cdx-search-result-title__match&quot;]</value>
      <webElementGuid>6b3d01fa-0eb5-4ab0-ba07-688be24f02df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='cdx-menu-item-61']/a/span[2]/span/bdi/span</value>
      <webElementGuid>01d9fcfc-6c1c-4f77-8616-0c368b03f79d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//bdi/span</value>
      <webElementGuid>35293825-5dea-4f90-a562-492dc0746284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Katalon Studio' or . = 'Katalon Studio')]</value>
      <webElementGuid>2175a173-649f-4c4d-9067-9618fc788408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='cdx-menu-item-36']/a/span[2]/span/bdi/span</value>
      <webElementGuid>925eabb5-3cbc-462d-b46b-3f62142c6ea6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
