<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonswap-sort-order-button</name>
   <tag></tag>
   <elementGuidId>2bb4fa4d-906a-48c5-b668-8d1a45c18bcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#swap-sort-order-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='swap-sort-order-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a01bc8a7-dd9e-4458-b4d8-289167ff64d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>swap-sort-order-button</value>
      <webElementGuid>533994b9-a3d4-4129-a027-4d79e9d10ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ipc-icon-button sc-78613a87-3 fkzGcF ipc-icon-button--base ipc-icon-button--onBase</value>
      <webElementGuid>3c386a35-d148-49c7-aa74-ac04294fa38e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Change sort by direction</value>
      <webElementGuid>c18f8193-279f-44b7-b6d0-01a1d6cdcf1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4ad75122-530a-4e38-964b-42ee33c07010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8a5d0a17-04e7-4fda-952c-16a983d20e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Change sort by direction</value>
      <webElementGuid>227b3442-1526-4547-ba8c-f1db4cf2d17a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ce283160-57b1-48ca-bcd7-3c1a043b4281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swap-sort-order-button&quot;)</value>
      <webElementGuid>859fc980-f100-4c61-819d-e4b1da63132b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='swap-sort-order-button']</value>
      <webElementGuid>53ef2639-7fee-4f26-a2ff-cde7a24b043c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[3]/section/div/div[2]/div/div[3]/div/button</value>
      <webElementGuid>da007553-29d8-4561-9780-744481df6a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>0ef7a93d-b59a-4c98-bd5c-94378c7090d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'swap-sort-order-button' and @title = 'Change sort by direction']</value>
      <webElementGuid>ed2a770d-d924-4b76-9e5d-ed44879f174c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
