<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_RankingIMDb ratingRelease dateNumber_98e9ec</name>
   <tag></tag>
   <elementGuidId>72475b9b-387b-4bd4-bb6c-b94a89a4db2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sort-by-selector</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='sort-by-selector']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>98ce7348-04e5-4c12-96d2-587f2d3a936b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sort-by-selector</value>
      <webElementGuid>0ee8d4a5-85de-4760-b1f1-7422d9c4f1f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ipc-simple-select__input</value>
      <webElementGuid>00d982e9-985f-4f6f-b46b-6989d8b869f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RankingIMDb ratingRelease dateNumber of ratingsAlphabeticalPopularityRuntime</value>
      <webElementGuid>9c922aef-291a-41c2-966f-23bb6d9eae8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sort-by-selector&quot;)</value>
      <webElementGuid>f355b41f-1b4c-4c85-84d5-43ab2eed3a54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='sort-by-selector']</value>
      <webElementGuid>3a3e3e24-9dd5-4281-bd37-91458228a8b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[3]/section/div/div[2]/div/div[3]/div/span/span/select</value>
      <webElementGuid>5c49489f-b96b-492e-b16d-673584d594a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>925b659f-8ab1-4a52-9f7a-481a7ac70f58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'sort-by-selector' and (text() = 'RankingIMDb ratingRelease dateNumber of ratingsAlphabeticalPopularityRuntime' or . = 'RankingIMDb ratingRelease dateNumber of ratingsAlphabeticalPopularityRuntime')]</value>
      <webElementGuid>6c3323ea-2150-41ba-9e1e-2c806a567d5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
