<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_ipc-icon ipc-icon--grid-view</name>
   <tag></tag>
   <elementGuidId>af72a43d-90c2-4a7f-bb0a-329ef4f7af64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.ipc-icon.ipc-icon--swap-vert</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>f7d80ed3-b70a-490b-b76f-da9c54ade1d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>1322e3ae-ab49-450c-b606-ba9acad26379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>f7008b04-fe01-4137-b991-da4d521d115d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>0c8de425-c69d-49ee-b66c-2ccf570b858c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ipc-icon ipc-icon--swap-vert</value>
      <webElementGuid>806c570b-26c8-4510-b181-c56629b0ae0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>1aad641e-97de-497e-ac4e-77ad41e76ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>87fb2304-25c9-4dfa-a5fc-a2a87b0a0375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>ff3676aa-a930-422a-be2c-cc5b41400a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swap-sort-order-button&quot;)/svg[@class=&quot;ipc-icon ipc-icon--swap-vert&quot;]</value>
      <webElementGuid>22149f5e-2ebb-4ef1-93fe-c85ccb68ee5d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
