<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Katalon TestOps</name>
   <tag></tag>
   <elementGuidId>9195b986-5580-4bd9-ac2e-5a57c8e800f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Katalon_TestOps</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='Katalon_TestOps']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0b368220-3f52-42ec-bf0a-efadb3a59caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mw-headline</value>
      <webElementGuid>cd1ddd94-9d1e-47eb-b421-c7f92d3add50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Katalon_TestOps</value>
      <webElementGuid>19ebec90-338f-4bc4-849c-661aa65be0de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Katalon TestOps</value>
      <webElementGuid>429f0b30-156c-4a00-9995-9910cc1a75dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Katalon_TestOps&quot;)</value>
      <webElementGuid>c9a81c9d-da6c-44ef-82cf-bb90e0f86922</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='Katalon_TestOps']</value>
      <webElementGuid>677ecc5d-151a-445e-8469-70d7ea7d8dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mw-content-text']/div/h3/span</value>
      <webElementGuid>3c7e40c1-0477-474d-a916-35b47fcecf79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/span</value>
      <webElementGuid>bcae16b6-d460-4f77-9e1e-694936083104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'Katalon_TestOps' and (text() = 'Katalon TestOps' or . = 'Katalon TestOps')]</value>
      <webElementGuid>156fe5e4-9ad0-42eb-bec8-4f7cbcbdc361</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
