<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_English</name>
   <tag></tag>
   <elementGuidId>c276c774-5834-43c8-9278-6a790c3c1d61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#js-link-box-en > strong</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='js-link-box-en']/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>5a04ae93-2101-4ac5-b5ea-4f76881b26a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>English</value>
      <webElementGuid>ca988a3e-e672-4f2e-83fb-dad192db67b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-link-box-en&quot;)/strong[1]</value>
      <webElementGuid>07ed3b6d-d9eb-458b-9a1a-1e2f717e7830</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='js-link-box-en']/strong</value>
      <webElementGuid>b08b8a5e-6758-47dc-9be3-048a0d0f9244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/strong</value>
      <webElementGuid>4f808498-0839-408f-a518-eb2c64135602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'English' or . = 'English')]</value>
      <webElementGuid>88f1d1ec-fa7a-4fbb-9ce2-53be767e8b66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
