<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Top 250 Movies</name>
   <tag></tag>
   <elementGuidId>de0c0918-8c45-46ef-a2d8-21eafbf0a747</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='imdbHeader']/div[2]/aside/div/div[2]/div/div/span/div/div/ul/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1ee13f3b-18b4-4220-a71a-b5980cd96019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>ae9640b4-a34a-43f0-80ca-e186700c917e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ipc-list__item nav-link sc-gXfWyg ggHJvJ ipc-list__item--indent-one</value>
      <webElementGuid>bd4f96dd-1286-4543-b414-be8537fce08e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/chart/top/?ref_=nv_mv_250</value>
      <webElementGuid>47ca92e1-caeb-408b-9713-24077f1cf096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e1ef913e-1ead-430e-b542-9713071ec1e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dc3abc23-6895-4bc6-9df3-f362f9e73390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Top 250 Movies</value>
      <webElementGuid>8641bb91-dc06-444f-92af-1c4e07099ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imdbHeader&quot;)/div[@class=&quot;ipc-page-content-container ipc-page-content-container--center navbar__inner&quot;]/aside[@class=&quot;sc-lmgPJu kVggCi drawer hamburger__drawer imdb-header__nav-drawer&quot;]/div[@class=&quot;drawer__panel&quot;]/div[@class=&quot;drawer__panelContent&quot;]/div[@class=&quot;sc-iBzDrC zqUAJ navlcl&quot;]/div[@class=&quot;sc-ciSkmu csYLwF navlinkcat&quot;]/span[@class=&quot;navlinkcat__targetWrapper&quot;]/div[@class=&quot;navlinkcat__listContainer&quot;]/div[@class=&quot;navlinkcat__listContainerInner&quot;]/ul[@class=&quot;ipc-list navlinkcat__list ipc-list--baseAlt&quot;]/a[@class=&quot;ipc-list__item nav-link sc-gXfWyg ggHJvJ ipc-list__item--indent-one&quot;]</value>
      <webElementGuid>135484cc-91d6-47d2-8873-5a61ac1910e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='imdbHeader']/div[2]/aside/div/div[2]/div/div/span/div/div/ul/a[2]</value>
      <webElementGuid>b46424cb-6cb2-4762-bbd2-0eeaee776add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/chart/top/?ref_=nv_mv_250')]</value>
      <webElementGuid>f41a3337-e9e0-452c-8827-caf87e4e72ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/a[2]</value>
      <webElementGuid>55814fb9-3269-4948-8cf8-2f3fb84caead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/chart/top/?ref_=nv_mv_250' and (text() = 'Top 250 Movies' or . = 'Top 250 Movies')]</value>
      <webElementGuid>973cb214-b434-4805-853f-ebea2545ad33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
