<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Menu</name>
   <tag></tag>
   <elementGuidId>5eac8ac6-9b06-4ce5-97ad-5e83e9fbdfc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#imdbHeader-navDrawerOpen</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='imdbHeader-navDrawerOpen']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>cc666436-6eb2-4217-a375-b98752b143dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imdbHeader-navDrawerOpen</value>
      <webElementGuid>f7edfbce-709a-4726-bf5e-209aa9c55b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ipc-responsive-button ipc-btn--theme-baseAlt ipc-responsive-button--transition-l ipc-btn--on-textPrimary ipc-responsive-button--single-padding sc-jNnpTB dTBLoU hamburger__icon</value>
      <webElementGuid>63cb3552-b43c-44af-9fad-c87eb8fe98b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c94a1d38-707f-4842-bbd1-f289b3cd0609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1476cd54-5b71-440a-8c47-a4c58d349f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Open Navigation Drawer</value>
      <webElementGuid>ddbf64f6-6e15-475d-bb50-679159dab166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dd19be6d-af19-436b-a0a4-efdf386d4cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>imdbHeader-navDrawer</value>
      <webElementGuid>0a5756ea-ce2a-4c24-8d51-a68365708c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menu</value>
      <webElementGuid>bcc95c85-22ab-49df-8c1f-0fa8cb831a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imdbHeader-navDrawerOpen&quot;)</value>
      <webElementGuid>ab0efcb9-58ed-4b51-8286-c412e2134ceb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='imdbHeader-navDrawerOpen']</value>
      <webElementGuid>6b76329b-b1c8-40f7-b454-f9bd4350c56a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='imdbHeader']/div[2]/label</value>
      <webElementGuid>f128e16b-a5cb-41c2-82de-1d8c6b74435c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>f0598762-5e4d-469c-b668-7976431ae19e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'imdbHeader-navDrawerOpen' and (text() = 'Menu' or . = 'Menu')]</value>
      <webElementGuid>dcc786d3-064d-4e92-9613-6d758f70069b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
