<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Titles</name>
   <tag></tag>
   <elementGuidId>e389a1a0-dc1a-436d-9c42-f748090b5011</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='navbar-search-category-select-contents']/ul/li[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c4acbd80-ce28-420e-a9ba-abc399d38225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ipc-list-item__text</value>
      <webElementGuid>dcc759ed-58fc-4c8e-9989-9b6cc22af02f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>a11f1a7f-bc4c-4f45-8373-4de6afc69ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Titles</value>
      <webElementGuid>cade8429-9a0b-419e-bb11-6e4fc6d95dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar-search-category-select-contents&quot;)/ul[@class=&quot;ipc-list searchCatSelector ipc-list--baseAlt&quot;]/li[@class=&quot;ipc-list__item searchCatSelector__item&quot;]/span[@class=&quot;ipc-list-item__text&quot;]</value>
      <webElementGuid>144a9a77-af67-4b59-907a-48a065c02a55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='navbar-search-category-select-contents']/ul/li[2]/span</value>
      <webElementGuid>717f5d56-6b78-4409-92f4-a7723a44114a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/ul/li[2]/span</value>
      <webElementGuid>7e55a36a-f682-4e13-a493-badc0c3e19b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Titles' or . = 'Titles')]</value>
      <webElementGuid>0776c5ae-71a1-46e8-a05e-bf81fb3d31cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
