<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_ipc-icon ipc-icon--arrow-drop-down ipc-_9ab380</name>
   <tag></tag>
   <elementGuidId>c7e06330-cd8e-44e1-9da7-8d3b23b754bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.ipc-icon.ipc-icon--menu.ipc-responsive-button__icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>e21bea9b-d20c-46f4-bad7-1fb47299b0a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>bdad6c04-82f8-4346-9dcd-17bf7b86f0d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>bf5c4f60-0eaf-4b8e-a0b7-8b7910ac504b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>9cb3aadd-6d9f-4ec6-964b-02af4aa115fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ipc-icon ipc-icon--menu ipc-responsive-button__icon</value>
      <webElementGuid>1e3a75a1-17a3-45e4-b039-b14578c8507a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>53fa27e1-80ff-42e5-a9d5-8fb33023bb0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>5a2233bb-dacd-4345-bd7d-8ff868eb33fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>49043f68-e127-4025-89fa-55ccf2116d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imdbHeader-navDrawerOpen&quot;)/svg[@class=&quot;ipc-icon ipc-icon--menu ipc-responsive-button__icon&quot;]</value>
      <webElementGuid>7e3e2ede-74c4-45c8-b795-a41145a1302f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
