<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Rick Riordan</name>
   <tag></tag>
   <elementGuidId>93e3e063-c140-4f63-9db5-073d3b5919bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ipc-metadata-list-item__list-content-item.ipc-metadata-list-item__list-content-item--link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/section/section/div[3]/section/section/div[3]/div[2]/div/section/div[2]/div/ul/li/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>26c2a8c0-900f-4982-94fb-71885a44cc82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ipc-metadata-list-item__list-content-item ipc-metadata-list-item__list-content-item--link</value>
      <webElementGuid>393287b0-4ad4-4901-8838-7902eb5fb0f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>679ba143-7689-4353-ba60-9b5b9f74d10b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>24fac320-7c53-450e-8244-275f502aec1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b3c28a13-5e64-4dc0-9bd6-e2a04e33752e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/name/nm2292894/?ref_=tt_ov_wr</value>
      <webElementGuid>369ffe83-0b0e-4cc1-bd81-6b2998fa2998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rick Riordan</value>
      <webElementGuid>5137f2c6-674f-4537-8616-63a221e51f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;ipc-page-wrapper ipc-page-wrapper--base&quot;]/div[@class=&quot;ipc-page-content-container ipc-page-content-container--full sc-872d7ac7-0 fqEQWL&quot;]/section[@class=&quot;ipc-page-background ipc-page-background--base sc-304f99f6-0 fSJiHR&quot;]/section[@class=&quot;ipc-page-background ipc-page-background--baseAlt sc-ae13f4cd-0 liescR atf-background-theme-dark&quot;]/div[@class=&quot;ipc-page-content-container ipc-page-content-container--center&quot;]/section[@class=&quot;ipc-page-background ipc-page-background--baseAlt sc-e226b0e3-0 ekzrNW&quot;]/section[@class=&quot;ipc-page-section ipc-page-section--baseAlt ipc-page-section--tp-none ipc-page-section--bp-xs sc-e226b0e3-2 gelzOk&quot;]/div[@class=&quot;sc-e226b0e3-4 gdkmhg&quot;]/div[@class=&quot;sc-e226b0e3-6 aQqbp&quot;]/div[@class=&quot;sc-e226b0e3-10 kRcXhr&quot;]/section[@class=&quot;sc-69e49b85-4 ktjuZl&quot;]/div[@class=&quot;sc-69e49b85-3 dIOekc&quot;]/div[1]/ul[@class=&quot;ipc-metadata-list ipc-metadata-list--dividers-all title-pc-list ipc-metadata-list--baseAlt&quot;]/li[@class=&quot;ipc-metadata-list__item ipc-metadata-list-item--link&quot;]/div[@class=&quot;ipc-metadata-list-item__content-container&quot;]/ul[@class=&quot;ipc-inline-list ipc-inline-list--show-dividers ipc-inline-list--inline ipc-metadata-list-item__list-content baseAlt&quot;]/li[@class=&quot;ipc-inline-list__item&quot;]/a[@class=&quot;ipc-metadata-list-item__list-content-item ipc-metadata-list-item__list-content-item--link&quot;]</value>
      <webElementGuid>eaa0ba79-4233-4479-a987-feca64f8f7c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/section/section/div[3]/section/section/div[3]/div[2]/div/section/div[2]/div/ul/li/div/ul/li/a</value>
      <webElementGuid>52f13858-0068-401b-b2aa-dc488ee9c682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Rick Riordan')]</value>
      <webElementGuid>aa1c22aa-4b04-40cb-9d1d-29e6a4127b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/name/nm2292894/?ref_=tt_ov_wr')]</value>
      <webElementGuid>0c7b1abf-0106-458b-9b7e-b35c4f247150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/ul/li/a</value>
      <webElementGuid>729a6396-56f9-4b8d-a5ee-56db1e617a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/name/nm2292894/?ref_=tt_ov_wr' and (text() = 'Rick Riordan' or . = 'Rick Riordan')]</value>
      <webElementGuid>168325bf-536f-445f-b582-ceca60089c7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
