<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Contents</name>
   <tag></tag>
   <elementGuidId>04b500aa-64ca-48e9-be1f-1ca084a5e837</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.vector-pinnable-header-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vector-toc']/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>1da949a3-24b0-4704-8fdd-82f6a55aa7fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vector-pinnable-header-label</value>
      <webElementGuid>16d2d2f7-79e2-44e5-aad5-516db063edb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contents</value>
      <webElementGuid>84b9e0be-8b3b-42b5-92c6-1168b1132229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vector-toc&quot;)/div[@class=&quot;vector-pinnable-header vector-toc-pinnable-header vector-pinnable-header-pinned&quot;]/h2[@class=&quot;vector-pinnable-header-label&quot;]</value>
      <webElementGuid>ee33a834-17fe-43cb-a83b-be72fa8732d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vector-toc']/div/h2</value>
      <webElementGuid>e0a45dce-bcf3-400b-abc3-71e537b9f22f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>9d9ab0f5-e2dc-4104-8bb7-837de19b6815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Contents' or . = 'Contents')]</value>
      <webElementGuid>6d09f891-2791-4372-a325-746b3a6fa7d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
