<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_English</name>
   <tag></tag>
   <elementGuidId>ecc40046-ec74-4cd6-a76d-8e853dee084f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#js-link-box-en > strong</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='js-link-box-en']/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>ab4f71c4-18fa-407f-bab7-79b474ea03d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>English</value>
      <webElementGuid>820d5264-824b-467d-be37-2b72fd7e68a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-link-box-en&quot;)/strong[1]</value>
      <webElementGuid>3a733a99-ae80-4205-b435-74bfca1e40ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='js-link-box-en']/strong</value>
      <webElementGuid>c5ca788a-2940-407b-9180-757799b0a00b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/strong</value>
      <webElementGuid>a2f196e3-35ee-4fcb-b872-97cd71c3c5c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'English' or . = 'English')]</value>
      <webElementGuid>41213603-8863-4ce1-a309-2564f1f59e20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
